gems:

repositories:
  remote:
    - http://repo1.maven.org/maven2

artifacts:
  # -- test dependencies
  hamcrest: 'org.hamcrest:hamcrest-all:jar:1.3'
  h2:       'com.h2database:h2:jar:1.3.170'
  flyway:   'com.googlecode.flyway:flyway-core:jar:2.0.3'

jmock: 2.6.0