package com.vtence.tape;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TableSchema {

    private final String name;
    private final List<Column<?>> columns = new ArrayList<>();

    public TableSchema(String name) {
        this.name = name;
    }

    public String name() {
        return name;
    }

    public Column<Long> LONG(String name) {
        return add(new Column<>(this, name, Types.LONG));
    }

    public Column<String> STRING(String name) {
        return add(new Column<>(this, name, Types.STRING));
    }

    public Column<BigDecimal> BIG_DECIMAL(String name) {
        return add(new Column<>(this, name, Types.BIG_DECIMAL));
    }

    public Column<Integer> INT(String name) {
        return add(new Column<>(this, name, Types.INT));
    }

    public <T> Column<T> add(Column<T> column) {
        columns.add(column);
        return column;
    }

    public int columnCount(boolean includeAutoGenerated) {
        return columns(includeAutoGenerated).size();
    }

    public List<Column<?>> columns(boolean includeAutoGenerated) {
        List<Column<?>> columns = new ArrayList<>();
        for (Column<?> column : this.columns) {
            if (includeAutoGenerated || !column.isAutoGenerated()) columns.add(column);
        }
        return columns;
    }

    public int indexOf(Column<?> column, boolean includeAutoGenerated) {
        return columns(includeAutoGenerated).indexOf(column);
    }
}
