package com.vtence.tape;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class Table<T> implements Record<T> {

    private final TableSchema schema;
    private final Record<T> record;

    public Table(TableSchema schema, Record<T> record) {
        this.schema = schema;
        this.record = record;
    }

    public String name() {
        return schema.name();
    }

    public List<String> columnNames(boolean includeAutoGenerated) {
        List<String> names = new ArrayList<String>();
        for (Column<?> column : schema.columns(includeAutoGenerated)) {
            names.add(column.name());
        }
        return names;
    }

    public int columnCount(boolean includeAutoGenerated) {
        return schema.columnCount(includeAutoGenerated);
    }

    public T hydrate(ResultSet resultSet) throws SQLException {
        return record.hydrate(resultSet);
    }

    public void dehydrate(PreparedStatement statement, T entity) throws SQLException {
        record.dehydrate(statement, entity);
    }

    public void handleKeys(ResultSet keys, T entity) throws SQLException {
        record.handleKeys(keys, entity);
    }
}
